resource_group_name     = "my_terraforms_rg"
resource_group_location = "West Europe"
app_service_plan_name   = "my-appserviceplans"
app_service_name        = "terraforms-demo-010"
sql_server_name         = "terraform-sqlserver-010"
sql_database_name       = "ProductsDBs"
sql_admin_login         = "user0s1"
sql_admin_password      = "@Aas123456789!"