resource_group_name     = "my_terraformss_rg"
resource_group_location = "West Europe"
app_service_plan_name   = "my-appserviceplan"
app_service_name        = "terraform-demos-010"
sql_server_name         = "terraform-sqlservers-010"
sql_database_name       = "ProductsDBs"
sql_admin_login         = "user01s"
sql_admin_password      = "@Aas123456789!"